import { test, expect } from '@playwright/test'
import { mkdirSync } from 'node:fs'
const directory='dist-release/v0.1.4/screenshots'
test('welcome, Provider cancellation, menus and keyboard shortcuts',async({page})=>{
 await page.goto('/',{waitUntil:'domcontentloaded'})
 await expect(page.getByRole('heading',{name:'从一个想法开始'})).toBeVisible()
 await page.getByRole('button',{name:'GPT Chat',exact:true}).click()
 await expect(page.getByRole('dialog',{name:'GPT Chat 配置'})).toBeVisible()
 await page.keyboard.press('Escape')
 await expect(page.getByRole('dialog',{name:'GPT Chat 配置'})).toHaveCount(0)
 await page.getByRole('button',{name:'会话更多操作'}).click()
 await page.getByRole('menuitem',{name:'会话 Prompt',exact:true}).click()
 await expect(page.getByRole('dialog',{name:'会话 Prompt'})).toBeVisible()
 await page.keyboard.press('Escape')
 await page.keyboard.press('Control+l')
 await expect(page.getByRole('textbox',{name:'聊天输入框',exact:true})).toBeFocused()
 await page.getByRole('textbox',{name:'聊天输入框',exact:true}).fill('草稿不会丢失')
 await page.keyboard.press('Control+n')
 await expect(page.getByRole('textbox',{name:'聊天输入框',exact:true})).toHaveValue('')
 await expect(page.locator('.conversation-link')).toHaveCount(2)
 await page.locator('.conversation-link').nth(1).click()
 await expect(page.getByRole('textbox',{name:'聊天输入框',exact:true})).toHaveValue('草稿不会丢失')
 await page.keyboard.press('Control+k')
 await expect(page.getByRole('searchbox',{name:'搜索历史对话'})).toBeFocused()
 await page.getByRole('searchbox',{name:'搜索历史对话'}).fill('没有此标题')
 await expect(page.getByText('没有匹配的对话')).toBeVisible()
 await page.getByRole('button',{name:'清空搜索'}).click()
 await expect(page.locator('.conversation-link')).toHaveCount(2)
})
test('IME candidates, expanded draft, rename and theme preferences',async({page})=>{
 await page.goto('/',{waitUntil:'domcontentloaded'})
 const input=page.getByRole('textbox',{name:'聊天输入框',exact:true})
 await input.fill('中文候选确认')
 await input.dispatchEvent('compositionstart')
 await input.dispatchEvent('keydown',{key:'Enter',code:'Enter',isComposing:true})
 await expect(page.locator('.message.user')).toHaveCount(0)
 await page.getByRole('button',{name:'展开编辑',exact:true}).click()
 await expect(page.getByRole('textbox',{name:'展开的聊天输入框'})).toHaveValue('中文候选确认')
 await page.getByRole('textbox',{name:'展开的聊天输入框'}).fill('展开编辑后的草稿')
 await page.getByRole('button',{name:'收起',exact:true}).click()
 await expect(input).toHaveValue('展开编辑后的草稿')
 await page.locator('.conversation').first().hover()
 await page.getByRole('button',{name:'会话操作',exact:true}).click()
 await page.getByRole('menuitem',{name:'重命名',exact:true}).click()
 await page.getByRole('textbox',{name:'重命名会话'}).fill('新的会话名称')
 await page.getByRole('button',{name:'保存',exact:true}).click()
 await expect(page.locator('.conversation-title')).toContainText('新的会话名称')
 await page.keyboard.press('Control+,')
 await page.getByRole('button',{name:'通用偏好',exact:true}).click()
 await page.getByLabel('发送方式').selectOption('ctrl-enter')
 await page.getByRole('combobox',{name:/主题/}).selectOption('dark')
 await page.getByRole('button',{name:'保存偏好'}).click()
 await expect(page.locator('html')).toHaveAttribute('data-theme','dark')
 await page.keyboard.press('Escape')
 await expect(page.getByText('Ctrl+Enter 发送 · Enter 换行')).toBeVisible()
})
for(const theme of ['light','dark'] as const)for(const scale of [1,1.25,1.5,2])test(`layout ${theme} ${scale*100}%`,async({browser})=>{
 const context=await browser.newContext({viewport:{width:scale===1?1440:800,height:scale===1?900:600},deviceScaleFactor:scale,colorScheme:theme})
 const page=await context.newPage();await page.goto('http://127.0.0.1:1420',{waitUntil:'domcontentloaded'})
 await expect(page.locator('html')).toHaveAttribute('data-theme',theme)
 await expect(page.locator('.provider-status').first()).toHaveCSS('height','6px')
 const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth)
 expect(overflow).toBe(false)
 const box=await page.locator('.input-box').boundingBox();expect(box?.width).toBeGreaterThan(300)
 await expect(page.getByRole('button',{name:'发送消息',exact:true})).toBeVisible()
 if(scale===1){mkdirSync(directory,{recursive:true});await page.screenshot({path:`${directory}/welcome-${theme}.png`});await page.keyboard.press('Control+,');await expect(page.getByRole('dialog',{name:'设置',exact:true})).toHaveCSS('opacity','1');await page.screenshot({path:`${directory}/settings-${theme}.png`})}
 await context.close()
})
test('640x480 icon sidebar and Provider panel remain within the viewport',async({browser})=>{
 const context=await browser.newContext({viewport:{width:640,height:480},deviceScaleFactor:2})
 const page=await context.newPage();await page.goto('http://127.0.0.1:1420',{waitUntil:'domcontentloaded'})
 await expect(page.locator('.sidebar')).toHaveClass(/sidebar-collapsed/)
 await page.getByRole('button',{name:'GPT Chat',exact:true}).click()
 const box=await page.getByRole('dialog',{name:'GPT Chat 配置'}).boundingBox();expect(box!.x).toBeGreaterThanOrEqual(0);expect(box!.x+box!.width).toBeLessThanOrEqual(640);expect(box!.y+box!.height).toBeLessThanOrEqual(480)
 await page.keyboard.press('Escape');await expect(page.getByRole('button',{name:'发送消息',exact:true})).toBeVisible()
 expect(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)).toBe(false)
 await context.close()
})
test('system theme responds live and reduced motion removes long transitions',async({page})=>{
 await page.emulateMedia({colorScheme:'light',reducedMotion:'reduce'});await page.goto('/',{waitUntil:'domcontentloaded'})
 await expect(page.locator('html')).toHaveAttribute('data-theme','light')
 await page.emulateMedia({colorScheme:'dark',reducedMotion:'reduce'});await expect(page.locator('html')).toHaveAttribute('data-theme','dark')
 expect(await page.getByRole('button',{name:'新建对话',exact:true}).evaluate(node=>parseFloat(getComputedStyle(node).transitionDuration)<.05)).toBe(true)
 await page.keyboard.press('Control+,');await page.getByRole('button',{name:'通用偏好',exact:true}).click();await page.getByRole('combobox',{name:/主题/}).selectOption('light');await page.getByRole('button',{name:'保存偏好'}).click();await expect(page.locator('html')).toHaveAttribute('data-theme','light')
 await page.emulateMedia({colorScheme:'dark'});await expect(page.locator('html')).toHaveAttribute('data-theme','light')
})
