import { beforeEach, afterEach, describe, expect, it, vi } from 'vitest'
import { createPinia, setActivePinia } from 'pinia'
import { mount, flushPromises } from '@vue/test-utils'
import { nextTick } from 'vue'
import { api } from '../src/services/tauri'
import { useChatStore } from '../src/stores/chat'
import ProviderSelector from '../src/components/ProviderSelector.vue'
import ChatInput from '../src/components/ChatInput.vue'
import type { Conversation, ApiProfile } from '../src/types'
vi.mock('../src/services/tauri',()=>({api:{isTauri:true,saveSettings:vi.fn(),saveExtension:vi.fn(),getExtension:vi.fn().mockResolvedValue(null),sendMessage:vi.fn(),getTree:vi.fn(),stopGeneration:vi.fn()}}))
const profile=(id:string,provider:ApiProfile['provider']):ApiProfile=>({id,name:id,provider,baseUrl:'https://unit.invalid/v1',model:id+'-model',thinking:'off',hasKey:true,inputPrice:0,outputPrice:0})
const conversation=(id:string):Conversation=>({id,title:id,model:'a-model',messages:[],createdAt:'2026-10-08',updatedAt:'2026-10-08',systemPrompt:''})
beforeEach(()=>{setActivePinia(createPinia());const chat=useChatStore();chat.profiles=[profile('a','anthropic-compatible'),profile('b','openai')];chat.settings={...chat.settings,baseUrl:chat.profiles[0].baseUrl,profileId:'a',model:'a-model'};chat.conversations=[conversation('first'),conversation('second')];chat.activeId='first';vi.mocked(api.saveSettings).mockImplementation(async settings=>({...settings,apiKey:''}));vi.mocked(api.saveExtension).mockResolvedValue(undefined)})
afterEach(()=>{vi.clearAllMocks();document.body.innerHTML=''})
describe('Provider confirmation',()=>{
 it('opening and cancelling does not alter the connection',async()=>{const chat=useChatStore();const before={...chat.settings};const wrapper=mount(ProviderSelector,{attachTo:document.body});await wrapper.find('[data-provider="gpt"]').trigger('click');await flushPromises();expect(chat.settings).toEqual(before);expect(api.saveSettings).not.toHaveBeenCalled();document.querySelector<HTMLButtonElement>('[aria-label="关闭服务配置"]')!.click();await nextTick();expect(chat.settings).toEqual(before);wrapper.unmount()})
 it('applies in one settings transaction',async()=>{const chat=useChatStore();await chat.applyProviderPreference('gpt',{profileId:'b',model:'custom-model',thinking:'high',searchMode:'off',searchProvider:'claude',searchBaseUrl:''});expect(api.saveSettings).toHaveBeenCalledTimes(1);expect(chat.settings.profileId).toBe('b');expect(chat.active?.model).toBe('custom-model');expect(chat.providerPreferences.claude?.profileId).toBe('a')})
 it('a rejected transaction preserves settings, model, and preferences',async()=>{const chat=useChatStore(),before={...chat.settings};vi.mocked(api.saveSettings).mockRejectedValueOnce(new Error('disk full'));await expect(chat.applyProviderPreference('gpt',{profileId:'b',model:'new',thinking:'off',searchMode:'off',searchProvider:'claude',searchBaseUrl:''})).rejects.toThrow();expect(chat.settings).toEqual(before);expect(chat.active?.model).toBe('a-model');expect(chat.providerPreferences).toEqual({});expect(chat.profileBusy).toBe(false)})
})
describe('composer drafts and submission',()=>{
 it('persists Composer search changes with the active conversation snapshot',async()=>{const chat=useChatStore();chat.settings={...chat.settings,searchMode:'off',searchProvider:'searxng',searchBaseUrl:'https://search.invalid'};const wrapper=mount(ChatInput);await wrapper.get('[aria-label="联网模式"]').setValue('force');await flushPromises();expect(api.saveSettings).toHaveBeenCalledWith(expect.objectContaining({searchMode:'force',searchBaseUrl:'https://search.invalid'}),'first');expect(wrapper.get<HTMLSelectElement>('[aria-label="联网模式"]').element.value).toBe('force');wrapper.unmount()})
 it('rejects invalid search settings without sending or discarding the Composer draft',async()=>{const chat=useChatStore();chat.settings={...chat.settings,searchMode:'force',searchProvider:'searxng',searchBaseUrl:''};const wrapper=mount(ChatInput);await wrapper.get('textarea').setValue('联网问题不能丢失');await wrapper.get('[aria-label="发送消息"]').trigger('click');await flushPromises();expect(api.sendMessage).not.toHaveBeenCalled();expect(chat.loading).toBe(false);expect(chat.error).toContain('SearXNG');expect(wrapper.get('textarea').element.value).toBe('联网问题不能丢失');wrapper.unmount()})
 it('rejects search mode changes before persisting and preserves the selected connection',async()=>{const chat=useChatStore();chat.settings={...chat.settings,provider:'openai-compatible',searchMode:'off',searchProvider:'claude'};const before={...chat.settings};await expect(chat.saveSettings({...chat.settings,searchMode:'force'})).rejects.toThrow('通用');expect(api.saveSettings).not.toHaveBeenCalled();expect(chat.settings).toEqual(before)})
 it('restores text and attachments independently for each conversation',async()=>{const chat=useChatStore();chat.drafts.second={text:'第二份草稿',attachments:[{id:'file',name:'a.py',kind:'code',mime:'text/plain',size:4,text:'pass'}]};const wrapper=mount(ChatInput);await wrapper.get('textarea').setValue('第一份草稿');chat.activeId='second';await nextTick();expect(wrapper.get('textarea').element.value).toBe('第二份草稿');expect(wrapper.text()).toContain('a.py');chat.activeId='first';await nextTick();expect(wrapper.get('textarea').element.value).toBe('第一份草稿');expect(wrapper.text()).not.toContain('a.py');expect(chat.drafts.second.attachments).toHaveLength(1);wrapper.unmount()})
 it('preserves the draft when configuration prevents sending',async()=>{const chat=useChatStore();chat.settings.baseUrl='';const wrapper=mount(ChatInput);await wrapper.get('textarea').setValue('不能丢失');await wrapper.get('[aria-label="发送消息"]').trigger('click');await flushPromises();expect(wrapper.get('textarea').element.value).toBe('不能丢失');wrapper.unmount()})
 it('does not send the Enter used by an IME candidate',async()=>{const chat=useChatStore(),send=vi.spyOn(chat,'send');const wrapper=mount(ChatInput);await wrapper.get('textarea').setValue('中文');await wrapper.get('textarea').trigger('keydown',{key:'Enter',isComposing:true});expect(send).not.toHaveBeenCalled();await wrapper.get('textarea').trigger('compositionstart');await wrapper.get('textarea').trigger('keydown',{key:'Enter'});expect(send).not.toHaveBeenCalled();wrapper.unmount()})
 it('protects duplicate submits and waits for stop completion',async()=>{const chat=useChatStore();let finish!:()=>void;vi.mocked(api.sendMessage).mockImplementation(()=>new Promise(resolve=>{finish=()=>resolve()}));vi.mocked(api.getTree).mockResolvedValue({messages:[],leaf:null});expect(await chat.send('hello')).toBe(true);await chat.send('duplicate');expect(api.sendMessage).toHaveBeenCalledTimes(1);await chat.stop();expect(chat.loading).toBe(true);expect(chat.stopping).toBe(true);finish();await flushPromises();expect(chat.loading).toBe(false);expect(chat.status).toBe('stopped')})
})
