import { beforeEach, afterEach, expect, it, vi } from 'vitest'
import { createPinia, setActivePinia } from 'pinia'
import { mount, flushPromises } from '@vue/test-utils'
import { api } from '../src/services/tauri'
import { useChatStore } from '../src/stores/chat'
import ProviderSelector from '../src/components/ProviderSelector.vue'
import ChatInput from '../src/components/ChatInput.vue'
import MessageItem from '../src/components/MessageItem.vue'
import type { Settings, ApiProfile, Message, RequestIdentity } from '../src/types'
import { identity } from '../src/utils/connection'
const runtime=vi.hoisted(()=>({settings:{} as any,profiles:[] as any[],messages:[] as any[],usage:[] as any[],origins:{} as Record<string,any>,extensions:{} as Record<string,any>,snapshots:{} as Record<string,any>,handlers:{} as Record<string,(event:any)=>void>,sent:[] as any[],hold:false,finish:undefined as (()=>void)|undefined,last:'c'}))
vi.mock('@tauri-apps/api/event',()=>({listen:vi.fn(async(name:string,handler:any)=>{runtime.handlers[name]=handler;return ()=>delete runtime.handlers[name]})}))
vi.mock('../src/services/tauri',()=>({api:{isTauri:true,getSettings:vi.fn(async()=>structuredClone(runtime.settings)),getProfiles:vi.fn(async()=>structuredClone(runtime.profiles)),getUsage:vi.fn(async()=>structuredClone(runtime.usage)),getExtension:vi.fn(async(key:string)=>key==='v4:lastConversation'?runtime.last:key==='v4:requestOrigins'?structuredClone(runtime.origins):runtime.extensions[key] || null),saveExtension:vi.fn(async(key:string,value:any)=>{runtime.extensions[key]=JSON.parse(JSON.stringify(value))}),getConversations:vi.fn(async()=>[{id:'recent',title:'other',model:'other-conversation-model',messages:[],createdAt:'2',updatedAt:'2',systemPrompt:''},{id:'c',title:'current',model:'legacy-conversation-model',messages:[],createdAt:'1',updatedAt:'1',systemPrompt:''}]),getTree:vi.fn(async()=>({messages:structuredClone(runtime.messages),leaf:runtime.messages.at(-1)?.id || null})),selectConversation:vi.fn(async(id:string)=>{runtime.last=id;runtime.settings={...runtime.settings,...runtime.snapshots[id]};return structuredClone({...runtime.settings,selectedMessageIds:[],selectedAttachmentIds:[]})}),saveSettings:vi.fn(),sendMessage:vi.fn(),stopGeneration:vi.fn(async()=>{}),getProviderModels:vi.fn(async()=>[])}}))
const profile=(id:string,provider:ApiProfile['provider']):ApiProfile=>({id,name:id+' Profile',provider,baseUrl:'https://'+id+'.invalid/v1',model:id+'-default',thinking:'off',hasKey:true,inputPrice:1,outputPrice:2,requestOptions:null})
const preference=(id:string,model:string)=>({profileId:id,model,thinking:'high' as const,searchMode:'off' as const,searchProvider:'claude' as const,searchBaseUrl:'',searchModel:''})
beforeEach(async()=>{
 setActivePinia(createPinia());runtime.settings={apiKey:'',baseUrl:'https://claude.invalid/v1',provider:'anthropic-compatible',model:'claude-current',profileId:'claude',thinking:'off',webSearch:false,theme:'light',systemPrompt:'',searchMode:'off',searchProvider:'claude',searchBaseUrl:'',searchModel:'',requestOptions:null,contextMode:'full',recentTurns:10,selectedMessageIds:[],selectedAttachmentIds:[]} satisfies Settings
 runtime.profiles=[profile('claude','anthropic-compatible'),profile('deep','deepseek'),profile('gpt','openai'),profile('kimi','moonshot'),profile('glm','zhipu'),profile('grok','grok')];runtime.messages=[{id:'u',parentId:null,role:'user',content:'original question',attachments:[{id:'file',name:'old.md',kind:'document',mime:'text/markdown',size:3,text:'old attachment'}],createdAt:'1'},{id:'a',parentId:'u',role:'assistant',content:'original reply',usageId:'old',createdAt:'2'}];runtime.usage=[{id:'old',conversationId:'c',model:'original-model',profileId:'claude',profileName:'original Profile',inputTokens:2,outputTokens:3,thinkingTokens:0,durationMs:1,estimatedCost:.1,createdAt:'1'}];runtime.origins={};runtime.extensions={};runtime.snapshots={};runtime.handlers={};runtime.sent=[];runtime.hold=false;runtime.finish=undefined;runtime.last='c'
 vi.mocked(api.saveSettings).mockImplementation(async settings=>{runtime.settings=JSON.parse(JSON.stringify(settings));runtime.snapshots.c=identity(settings);return structuredClone(runtime.settings)})
 vi.mocked(api.sendMessage).mockImplementation(async(conversationId,content,settings,_persist,_attachments,parentId)=>{
  const snapshot=JSON.parse(JSON.stringify(settings));runtime.sent.push(snapshot)
  return new Promise<void>(resolve=>{const finish=()=>{const index=runtime.sent.length,u={id:'u'+index,role:'user',parentId,content,createdAt:String(index)},usageId='usage-'+index,a={id:'a'+index,role:'assistant',parentId:u.id,content:'reply '+index,usageId,createdAt:String(index)},origin=identity(snapshot,runtime.profiles.find(p=>p.id===snapshot.profileId)?.name);runtime.messages.push(u,a);runtime.origins[usageId]=origin;const usage={id:usageId,conversationId,profileId:snapshot.profileId,profileName:origin.profileName,model:snapshot.model,inputTokens:7,outputTokens:4,thinkingTokens:1,durationMs:100,estimatedCost:.000015,createdAt:String(index)};runtime.usage.push(usage);runtime.handlers['chat-request-origin']?.({payload:{id:usageId,request:origin}});runtime.handlers['chat-usage']?.({payload:{usage}});resolve()};runtime.finish=finish;if(!runtime.hold)finish()})
 })
 await useChatStore().initialize()
})
afterEach(()=>{useChatStore().dispose();document.body.innerHTML='';vi.clearAllMocks()})
it('sends Claude → DeepSeek → GPT → Claude in one conversation and preserves every prior node, attachment and Usage',async()=>{
 const chat=useChatStore(),before=structuredClone(runtime.messages),original=structuredClone(runtime.usage[0])
 chat.settings.selectedMessageIds=['u'];chat.settings.selectedAttachmentIds=['file'];chat.references=[{messageId:'a',text:'reference'}]
 for(const [kind,id,model] of [['claude','claude','claude-selected'],['deepseek','deep','deep-selected'],['gpt','gpt','gpt-selected'],['claude','claude','claude-return']] as const){await chat.applyProviderPreference(kind,preference(id,model));expect(chat.activeId).toBe('c');expect(chat.settings.selectedMessageIds).toEqual(['u']);expect(chat.settings.selectedAttachmentIds).toEqual(['file']);await chat.send('next round');await flushPromises();expect(runtime.sent.at(-1)?.model).toBe(model);expect(chat.loading).toBe(false)}
 expect(runtime.sent.map(s=>s.provider)).toEqual(['anthropic-compatible','deepseek','openai','anthropic-compatible']);expect(runtime.sent.map(s=>s.baseUrl)).toEqual(['https://claude.invalid/v1','https://deep.invalid/v1','https://gpt.invalid/v1','https://claude.invalid/v1']);expect(runtime.messages.slice(0,2)).toEqual(before);expect(chat.trees.c).toHaveLength(10);expect(chat.conversations).toHaveLength(2);expect(runtime.usage[0]).toEqual(original);expect(chat.usage).toHaveLength(5);expect(chat.requestOrigins['usage-1'].model).toBe('claude-selected');expect(chat.requestOrigins['usage-2'].provider).toBe('deepseek')
 const wrapper=mount(MessageItem,{props:{message:chat.active!.messages[3],usage:chat.usage.find(u=>u.id==='usage-1')}});expect(wrapper.get('.message-connection').text()).toContain('claude-selected');expect(wrapper.get('.message-connection').text()).not.toContain('claude-return');wrapper.unmount()
})
it('lets the panel and Composer open during generation while locking the applied request until stop finishes',async()=>{
 const chat=useChatStore();runtime.hold=true;chat.settings.requestOptions={custom:{effort:'low'}}
 await chat.send('pending');const panel=mount(ProviderSelector,{attachTo:document.body}),composer=mount(ChatInput,{attachTo:document.body});await panel.get('[data-provider="deepseek"]').trigger('click');await flushPromises();expect(document.querySelector('#chat-provider-panel')).not.toBeNull();expect(document.querySelector<HTMLButtonElement>('.chat-provider-panel footer .provider-primary')!.disabled).toBe(true);expect(composer.get('[aria-label="配置当前聊天服务"]').attributes('disabled')).toBeUndefined()
 await expect(chat.applyProviderPreference('deepseek',preference('deep','new-deep'))).rejects.toThrow('等待');expect(runtime.sent[0].model).toBe('claude-current');expect(runtime.sent[0].profileId).toBe('claude')
 ;(chat.settings.requestOptions as any).custom.effort='changed';expect(runtime.sent[0].requestOptions.custom.effort).toBe('low');expect(chat.requestSettings?.requestOptions).toEqual({custom:{effort:'low'}})
 await chat.stop();expect(chat.stopping).toBe(true);expect(chat.loading).toBe(true);runtime.finish!();await flushPromises();expect(chat.loading).toBe(false);await chat.applyProviderPreference('deepseek',preference('deep','new-deep'));await flushPromises();expect(composer.text()).toContain('DeepSeek Chat');expect(composer.text()).toContain('new-deep');panel.unmount();composer.unmount()
})
it('keeps the original connection, draft, references, path and filters on a failed switch',async()=>{
 const chat=useChatStore();chat.drafts.c={text:'draft',attachments:[]};chat.references=[{messageId:'a',text:'reference'}];chat.settings.selectedMessageIds=['u'];const before=JSON.parse(JSON.stringify({settings:chat.settings,tree:chat.trees.c,drafts:chat.drafts,references:chat.references}));vi.mocked(api.saveSettings).mockRejectedValueOnce(new Error('simulated save failure'));await expect(chat.applyProviderPreference('gpt',preference('gpt','new'))).rejects.toThrow();expect(JSON.parse(JSON.stringify({settings:chat.settings,tree:chat.trees.c,drafts:chat.drafts,references:chat.references}))).toEqual(before);expect(chat.profileBusy).toBe(false);expect(chat.activeId).toBe('c')
})
it('restores the complete last selection after restart without mixing in another conversation model',async()=>{
 const chat=useChatStore();await chat.applyProviderPreference('deepseek',preference('deep','custom-deep'));chat.dispose();setActivePinia(createPinia());const restarted=useChatStore();await restarted.initialize();expect(restarted.activeId).toBe('c');expect(restarted.settings.provider).toBe('deepseek');expect(restarted.settings.profileId).toBe('deep');expect(restarted.settings.model).toBe('custom-deep');expect(restarted.settings.baseUrl).toBe('https://deep.invalid/v1');expect(restarted.active?.messages).toHaveLength(2)
})
it('uses the canonical backend response for the visible label and the next request',async()=>{
 const chat=useChatStore();vi.mocked(api.saveSettings).mockImplementationOnce(async settings=>({...settings,provider:'deepseek',baseUrl:'https://canonical.invalid/v1'}));await chat.applyProviderPreference('gpt',preference('gpt','custom'));expect(chat.settings.provider).toBe('deepseek');expect(chat.profiles.find(p=>p.id==='gpt')?.provider).toBe('deepseek');await chat.send('request');await flushPromises();expect(runtime.sent[0].provider).toBe('deepseek');expect(runtime.sent[0].baseUrl).toBe('https://canonical.invalid/v1')
})
it('allows model changes within the same Profile and the remaining Provider families',async()=>{
 const chat=useChatStore();await chat.applyProviderPreference('claude',preference('claude','custom-1'));await chat.applyProviderPreference('claude',preference('claude','custom-2'));expect(chat.settings.model).toBe('custom-2');expect(chat.active?.messages).toHaveLength(2)
 for(const [kind,id,provider] of [['kimi','kimi','moonshot'],['glm','glm','zhipu'],['grok','grok','grok']] as const){await chat.applyProviderPreference(kind,{...preference(id,id+'-selected'),searchProvider:'searxng'});expect(chat.settings.provider).toBe(provider);expect(chat.activeId).toBe('c')}
})
it('keeps a selected model as a draft, then applies all settings once and uses them for the next request',async()=>{
 const chat=useChatStore(),wrapper=mount(ProviderSelector,{attachTo:document.body});let finish!:()=>void
 vi.mocked(api.saveSettings).mockImplementationOnce(settings=>new Promise(resolve=>{finish=()=>{runtime.settings=JSON.parse(JSON.stringify(settings));resolve(structuredClone(runtime.settings))}}))
 await wrapper.get('[data-provider="claude"]').trigger('click');await flushPromises()
 const chosen=Array.from(document.querySelectorAll<HTMLButtonElement>('.provider-model-list button')).find(b=>b.textContent?.includes('claude-default'))!
 chosen.click();await flushPromises();expect(document.querySelector('.provider-model-list')).toBeNull();expect(document.querySelector('#chat-provider-panel')).not.toBeNull();expect(api.saveSettings).not.toHaveBeenCalled();expect(chat.settings.model).toBe('claude-current')
 const apply=document.querySelector<HTMLButtonElement>('.chat-provider-panel footer .provider-primary')!;apply.click();await flushPromises();expect(document.querySelector('.provider-controls')?.getAttribute('aria-busy')).toBe('true');expect(apply.disabled).toBe(true);expect(chat.settings.model).toBe('claude-current')
 apply.click();await flushPromises();expect(api.saveSettings).toHaveBeenCalledTimes(1);finish();await flushPromises();expect(document.querySelector('#chat-provider-panel')).toBeNull();expect(chat.settings.model).toBe('claude-default');expect(chat.active?.messages).toHaveLength(2)
 await chat.send('next request');await flushPromises();expect(runtime.sent.at(-1).model).toBe('claude-default');expect(runtime.sent.at(-1).profileId).toBe('claude');wrapper.unmount()
})
it('shows a failed Apply while keeping the selected model draft and actual history intact',async()=>{
 const chat=useChatStore(),before=JSON.parse(JSON.stringify(chat.active)),wrapper=mount(ProviderSelector,{attachTo:document.body});vi.mocked(api.saveSettings).mockRejectedValueOnce(new Error('disk full'))
 await wrapper.get('[data-provider="claude"]').trigger('click');await flushPromises();Array.from(document.querySelectorAll<HTMLButtonElement>('.provider-model-list button')).find(b=>b.textContent?.includes('claude-default'))!.click();await flushPromises()
 expect(api.saveSettings).not.toHaveBeenCalled();document.querySelector<HTMLButtonElement>('.chat-provider-panel footer .provider-primary')!.click();await flushPromises()
 expect(document.querySelector('.provider-panel-error')?.textContent).toContain('操作未完成');expect(chat.settings.model).toBe('claude-current');expect(chat.active).toEqual(before);expect(chat.profileBusy).toBe(false);expect(document.querySelector('.provider-controls')?.getAttribute('aria-busy')).toBe('false');wrapper.unmount()
})
it('a clicked model during generation remains a draft until explicitly applied after stopping',async()=>{
 const chat=useChatStore();runtime.hold=true;await chat.send('pending');const wrapper=mount(ProviderSelector,{attachTo:document.body});await wrapper.get('[data-provider="deepseek"]').trigger('click');await flushPromises()
 document.querySelector<HTMLButtonElement>('.provider-model-list button')!.click();await flushPromises();expect(api.saveSettings).not.toHaveBeenCalled();expect(chat.settings.model).toBe('claude-current');expect(chat.requestSettings?.model).toBe('claude-current')
 await chat.stop();runtime.finish!();await flushPromises();expect(chat.settings.model).toBe('claude-current');document.querySelector<HTMLButtonElement>('.chat-provider-panel footer .provider-primary')!.click();await flushPromises();expect(chat.settings.model).toBe('deep-default');expect(chat.settings.provider).toBe('deepseek');wrapper.unmount()
})
it('rejects late stream, sources, status and finish events from a previous request in the same conversation',async()=>{
 const chat=useChatStore();await chat.send('first');const previous=vi.mocked(api.sendMessage).mock.calls[0][7]!;expect(previous).toBeTruthy();await flushPromises();runtime.hold=true;await chat.applyProviderPreference('deepseek',preference('deep','second-model'));await chat.send('second');const current=chat.active!.messages.at(-1)!,id=chat.activeRequestId;expect(id).not.toBe(previous)
 runtime.handlers['chat-delta']({payload:{conversationId:'c',requestId:previous,delta:'old output'}});runtime.handlers['chat-sources']({payload:{conversationId:'c',requestId:previous,sources:[{title:'old',url:'https://old.invalid'}]}});runtime.handlers['chat-status']({payload:{conversationId:'c',requestId:previous,phase:'thinking',delta:'old thought'}});runtime.handlers['chat-request-finished']({payload:{conversationId:'c',requestId:previous}});chat.flushDeltas()
 expect(current.content).toBe('');expect(current.sources).toBeUndefined();expect(current.reasoningContent).toBeUndefined();expect(current.pending).toBe(true);expect(chat.requestSettings?.model).toBe('second-model')
 runtime.handlers['chat-delta']({payload:{conversationId:'c',requestId:id,delta:'current output'}});chat.flushDeltas();expect(current.content).toBe('current output');runtime.finish!();await flushPromises()
})
