<script setup lang="ts">
import { computed, nextTick, ref, watch } from 'vue'
import { ChevronRight, ChevronDown, MessageSquare, Sparkles, Quote, LocateFixed, X, ChevronsDownUp, ChevronsUpDown } from '@lucide/vue'
import { useChatStore } from '../stores/chat'
import { treeRows } from '../utils/experience'
const emit=defineEmits<{close:[]}>()
const chat=useChatStore(), collapsed=ref(new Set<string>()), viewport=ref<HTMLElement>(), scrollTop=ref(0)
const messages=computed(()=>chat.trees[chat.activeId] || chat.active?.messages || [])
const path=computed(()=>new Set(chat.active?.messages.map(m=>m.id)))
const rows=computed(()=>treeRows(messages.value,collapsed.value))
const rowHeight=62
const start=computed(()=>Math.max(0,Math.floor(scrollTop.value/rowHeight)-4))
const visible=computed(()=>rows.value.slice(start.value,start.value+18))
function toggle(id:string){const next=new Set(collapsed.value);next.has(id)?next.delete(id):next.add(id);collapsed.value=next}
async function locate(){collapsed.value=new Set();await nextTick();const index=rows.value.findIndex(r=>r.message.id===chat.active?.messages.at(-1)?.id);viewport.value?.scrollTo({top:Math.max(0,index*rowHeight-100),behavior:'smooth'})}
watch(()=>chat.activeId,()=>{collapsed.value=new Set();scrollTop.value=0})
const counts=computed(()=>{const result=new Map<string|null,number>();for(const m of messages.value){const key=m.parentId || null;result.set(key,(result.get(key)||0)+1)}return result})
</script>
<template><section class="conversation-tree" aria-label="对话树"><header><div><strong>对话树</strong><small>{{ messages.length }} 个节点 · 点击恢复上下文</small></div><div><button class="icon-button" title="展开所有分支" aria-label="展开所有分支" @click="collapsed=new Set()"><ChevronsUpDown :size="16"/></button><button class="icon-button" title="折叠所有分支" aria-label="折叠所有分支" @click="collapsed=new Set(messages.map(m=>m.id))"><ChevronsDownUp :size="16"/></button><button class="icon-button" title="定位当前节点" aria-label="定位当前节点" @click="locate"><LocateFixed :size="16"/></button><button class="icon-button" aria-label="关闭对话树" @click="emit('close')"><X :size="17"/></button></div></header><p v-if="!rows.length" class="hint">发送第一条消息后，这里将展示对话分支。</p><div ref="viewport" class="tree-viewport" role="tree" @scroll="scrollTop=($event.target as HTMLElement).scrollTop"><div :style="{height:`${rows.length*rowHeight}px`,position:'relative'}"><div v-for="(row,index) in visible" :key="row.message.id" class="tree-row" :class="{'on-path':path.has(row.message.id),current:row.message.id===chat.active?.messages.at(-1)?.id}" :style="{top:`${(start+index)*rowHeight}px`,paddingLeft:`${Math.min(row.depth,18)*20+8}px`}" role="treeitem" :aria-level="row.depth+1" :aria-selected="row.message.id===chat.active?.messages.at(-1)?.id" :aria-expanded="row.hasChildren?!collapsed.has(row.message.id):undefined"><svg v-if="row.depth" class="tree-connector" :style="{left:`${Math.min(row.depth,18)*20-4}px`}" width="16" height="62" viewBox="0 0 16 62" aria-hidden="true"><path d="M2 0V31H16M2 31V62" fill="none" stroke="currentColor" stroke-width="1.5"/></svg><button class="icon-button tree-fold" :disabled="!row.hasChildren" :aria-label="collapsed.has(row.message.id)?'展开分支':'折叠分支'" @click="toggle(row.message.id)"><component :is="collapsed.has(row.message.id)?ChevronRight:ChevronDown" :size="13"/></button><button class="tree-node" :class="row.message.role" :disabled="chat.loading" :title="row.message.content || '空回答'" @click="chat.jumpNode(row.message.id)"><component :is="row.message.role==='user'?MessageSquare:Sparkles" :size="15"/><span><strong>{{ row.message.role==='user'?'你':'助手' }}<small v-if="(counts.get(row.message.parentId || null) || 0)>1"> · {{ counts.get(row.message.parentId || null) }} 个版本</small></strong><small>{{ row.message.content.slice(0,90) || '空回答' }}</small></span></button><button class="icon-button tree-quote" aria-label="引用此节点" :disabled="chat.loading" @click="chat.quote(row.message)"><Quote :size="14"/></button></div></div></div></section></template>
