<script setup lang="ts">
import { reactive, ref } from 'vue'; import { api } from '../services/tauri'; import { modelOptions } from '../models'; import { useChatStore } from '../stores/chat'; import type { Settings } from '../types'
const emit = defineEmits<{ close: [] }>(); const chat = useChatStore(); const form = reactive<Settings>({ ...chat.settings }); const testing = ref(false); const testResult = ref('')
const selectedModel = ref(modelOptions.some(item => item.id === form.model) ? form.model : '__custom__')
const changeModel = () => { if (selectedModel.value !== '__custom__') form.model = selectedModel.value }
const save = async () => { await chat.saveSettings({ ...form }); emit('close') }
const test = async () => { testing.value = true; testResult.value = ''; try { const result = await api.testConnection({ ...form }); testResult.value = result.message } catch (error) { testResult.value = String(error) } finally { testing.value = false } }
</script>
<template><div class="modal-backdrop" @click.self="emit('close')"><section class="settings-modal"><header><div><h2>工作区设置</h2><p>连接、模型和外观都保存在当前设备。</p></div><button @click="emit('close')">×</button></header><div class="setting-grid"><label>Provider<select v-model="form.provider"><option value="anthropic-compatible">Anthropic Compatible</option><option value="openai-compatible">OpenAI Compatible（预留）</option></select></label><label>主题<select v-model="form.theme"><option value="system">跟随系统</option><option value="light">浅色</option><option value="dark">深色</option></select></label></div><label>Base URL<input v-model.trim="form.baseUrl" placeholder="https://api.anthropic.com"/></label><label>API Key<input v-model="form.apiKey" type="password" placeholder="留空可保留已保存的密钥" autocomplete="off"/></label><p class="hint">密钥只保存到 Windows Credential Manager，不会写入前端源码或 SQLite。</p><label>默认模型<select v-model="selectedModel" @change="changeModel"><option v-for="item in modelOptions" :key="item.id" :value="item.id">{{ item.label }} · {{ item.id }}</option><option value="__custom__">自定义模型 ID…</option></select></label><label v-if="selectedModel === '__custom__'">自定义模型 ID<input v-model.trim="form.model" placeholder="输入中转站提供的模型 ID"/></label><div class="test-row"><button class="secondary" :disabled="testing" @click="test">{{ testing ? '正在测试…' : '测试连接' }}</button><span :class="{ success: testResult.startsWith('连接成功'), failure: testResult && !testResult.startsWith('连接成功') }">{{ testResult }}</span></div><footer><button class="secondary" @click="emit('close')">取消</button><button class="primary" @click="save">保存设置</button></footer></section></div></template>
