<script setup lang="ts">
import ProviderSelector from './ProviderSelector.vue'; import type { ProviderKind } from '../types'; import { computed, nextTick, ref, watch } from 'vue'; import { useChatStore } from '../stores/chat'; import { api } from '../services/tauri'; import type { Conversation } from '../types'
defineProps<{ page: 'chat' | 'usage' }>()
const emit = defineEmits<{ openSettings: [provider?: ProviderKind,profileId?: string]; openUsage: []; openChat: [] }>(); const chat = useChatStore()
const query = ref(''); const results = ref<Conversation[]>([]); let sequence = 0
const searchOpen = ref(false); const searchInput = ref<HTMLInputElement>()
const toggleSearch = async () => { searchOpen.value = !searchOpen.value; if (searchOpen.value) { await nextTick(); searchInput.value?.focus() } else query.value = '' }
watch(query, async value => { const current = ++sequence; if (!value.trim()) { results.value = []; return } try { const found = api.isTauri ? await api.searchConversations(value.trim()) : chat.conversations.filter(c => c.title.includes(value)); if (current === sequence) results.value = found } catch { if (current === sequence) results.value = [] } })
const folder = ref(''), tag = ref(''), pinned = ref(false)
const folders = computed(() => [...new Set(Object.values(chat.organization).map(o => o.folder).filter(Boolean))])
const tags = computed(() => [...new Set(Object.values(chat.organization).flatMap(o => o.tags || []))])
const filtered = computed(() => (query.value.trim() ? results.value : chat.conversations).filter(c => {const o=chat.organization[c.id] || {}; return (!folder.value || o.folder===folder.value) && (!tag.value || o.tags?.includes(tag.value)) && (!pinned.value || o.pinned)}).slice().sort((a,b)=>Number(!!chat.organization[b.id]?.pinned)-Number(!!chat.organization[a.id]?.pinned)))
const categoryTarget=ref<{kind:'folder'|'tag';old:string}|null>(null), categoryName=ref('')
const classifyTarget=ref<string|null>(null), folderDraft=ref(''), tagsDraft=ref(''), organizationError=ref('')
const renameCategory = (kind:'folder'|'tag') => {const old=kind==='folder'?folder.value:tag.value;if(!old)return;categoryTarget.value={kind,old};categoryName.value=old;organizationError.value=''}
const saveCategory=async()=>{if(!categoryTarget.value)return;const {kind,old}=categoryTarget.value;try{await chat.renameCategory(kind,old,categoryName.value.trim());if(kind==='folder')folder.value=categoryName.value.trim();else tag.value=categoryName.value.trim();categoryTarget.value=null}catch(e){organizationError.value=String(e)}}
const classify = (id:string) => {const o=chat.organization[id] || {};classifyTarget.value=id;folderDraft.value=o.folder || '';tagsDraft.value=(o.tags || []).join(', ');organizationError.value=''}
const saveClassification=async()=>{const id=classifyTarget.value;if(!id)return;try{await chat.organize(id,{...chat.organization[id],folder:folderDraft.value.trim(),tags:[...new Set(tagsDraft.value.split(/[,，]/).map(t=>t.trim()).filter(Boolean))]});classifyTarget.value=null}catch(e){organizationError.value=String(e)}}
const rename = async (id: string, old: string) => { const title = prompt('会话名称', old)?.trim(); if (title) await chat.rename(id, title) }
const deleteTarget = ref<Conversation | null>(null); const deleting = ref(false); const deleteError = ref('')
const confirmDelete = async () => { if (!deleteTarget.value || deleting.value) return; deleting.value = true; deleteError.value = ''; try { await chat.remove(deleteTarget.value.id); deleteTarget.value = null } catch (error) { deleteError.value = String(error) } finally { deleting.value = false } }
</script>
<template>
  <aside class="sidebar">
    <div class="brand"><span>✦</span> ClaudeChat</div>
    <button class="new-chat" @click="chat.newConversation(); emit('openChat')">＋ 新建对话</button>
    <ProviderSelector @configure="(kind, profileId) => emit('openSettings', kind, profileId)" />
    <button class="usage-nav" :class="{ active: page === 'usage' }" type="button" @click="emit('openUsage')">▤ 用量统计</button>
    <div class="history-heading"><span class="history-label">历史会话</span><button class="history-search-toggle" type="button" :aria-label="searchOpen ? '关闭搜索' : '搜索历史对话'" :aria-expanded="searchOpen" @click="toggleSearch"><svg viewBox="0 0 24 24" width="17" height="17" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><circle cx="10.8" cy="10.8" r="6.3"/><path d="m16 16 4.2 4.2"/></svg></button></div><input v-if="searchOpen" ref="searchInput" v-model="query" class="history-search" type="search" placeholder="搜索历史对话" aria-label="搜索历史对话" @keydown.esc="toggleSearch" />
    <div class="conversation-filters"><select v-model="folder" aria-label="筛选文件夹"><option value="">全部文件夹</option><option v-for="f in folders" :key="f" :value="f">{{ f }}</option></select><select v-model="tag" aria-label="筛选标签"><option value="">全部标签</option><option v-for="t in tags" :key="t">{{ t }}</option></select><button v-if="folder" @click="renameCategory('folder')">管理文件夹</button><button v-if="tag" @click="renameCategory('tag')">管理标签</button><label><input v-model="pinned" type="checkbox"/>仅置顶</label></div><nav class="conversation-list"><div v-for="item in filtered" :key="item.id" :class="['conversation', { active: item.id === chat.activeId && page === 'chat' }]" @click="chat.select(item.id); emit('openChat')"><span class="conversation-title">{{ chat.organization[item.id]?.pinned ? '★ ' : '' }}{{ item.title }}<small v-if="chat.organization[item.id]?.folder"> · {{ chat.organization[item.id].folder }}</small></span><span class="conversation-actions"><button title="置顶 / 取消置顶" @click.stop="chat.organize(item.id,{...chat.organization[item.id],pinned:!chat.organization[item.id]?.pinned})">★</button><button title="管理文件夹与标签" @click.stop="classify(item.id)">▤</button><button @click.stop="rename(item.id, item.title)">✎</button><button @click.stop="deleteTarget = item; deleteError = ''" :aria-label="`删除 ${item.title}`">×</button></span></div><p v-if="query.trim() && !results.length" class="search-empty">没有匹配的对话</p></nav>
    <button class="settings-button" @click="emit('openSettings')">⚙ 设置</button>
    <div v-if="classifyTarget || categoryTarget" class="modal-backdrop"><form class="settings-modal" @submit.prevent="classifyTarget ? saveClassification() : saveCategory()"><h2>{{ classifyTarget ? '会话分类' : '管理分类' }}</h2><template v-if="classifyTarget"><label>文件夹<input v-model="folderDraft" placeholder="留空移出文件夹"/></label><label>标签<input v-model="tagsDraft" placeholder="用逗号分隔多个标签"/></label></template><label v-else>分类名称<input v-model="categoryName" placeholder="留空移除此分类"/></label><p v-if="organizationError" class="error">{{ organizationError }}</p><footer><button type="button" @click="classifyTarget=null;categoryTarget=null">取消</button><button type="submit">保存</button></footer></form></div>
    <div v-if="deleteTarget" class="modal-backdrop" @click.self="!deleting && (deleteTarget = null)"><section class="delete-modal" role="alertdialog" aria-modal="true" aria-labelledby="delete-dialog-title"><h2 id="delete-dialog-title">删除对话？</h2><p>“{{ deleteTarget.title }}”及其消息和附件将从本地历史中删除。</p><p v-if="deleteError" class="upload-error">{{ deleteError }}</p><footer><button class="secondary" type="button" :disabled="deleting" @click="deleteTarget = null">取消</button><button class="delete-confirm" type="button" :disabled="deleting" @click="confirmDelete">{{ deleting ? '正在删除…' : '确认删除' }}</button></footer></section></div>
  </aside>
</template>
